### ISSUE TITLE
med4all-be error is not useful

### ISSUE THREAD

**Issue by nsuthison** [gu-tum-gun-aeng/med4all-be#31]
We face the problem that med4all-be make a call to patient API and when the patient API cannot connect to the kafka, med4all-be return 503 to the client which it shouldn't

**Comment by catflyflyfly** [comment]
We fixed this in https://github.com/gu-tum-gun-aeng/med4all-patient-api/pull/10 and https://github.com/gu-tum-gun-aeng/med4all-patient-api/pull/11. We also fixed kafka issue in https://github.com/gu-tum-gun-aeng/med4all-infra/pull/6. Closed.
